export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  OUTAGE_WINDOW_NOT_FOUND: "OUTAGE_WINDOW_NOT_FOUND",
  OUTAGE_WINDOW_INVALID_RANGE: "OUTAGE_WINDOW_INVALID_RANGE",
  OUTAGE_ALREADY_CONFIRMED: "OUTAGE_ALREADY_CONFIRMED",
  OUTAGE_DRAFT_VERSION_STALE: "OUTAGE_DRAFT_VERSION_STALE",
  OUTAGE_RESUME_KEY_MISMATCH: "OUTAGE_RESUME_KEY_MISMATCH",
  OUTAGE_WRITE_STAGE_UNKNOWN: "OUTAGE_WRITE_STAGE_UNKNOWN",
  BACKUP_CAPACITY_EXHAUSTED: "BACKUP_CAPACITY_EXHAUSTED",
  DEVICE_NOT_OUT_OF_SERVICE: "DEVICE_NOT_OUT_OF_SERVICE",
  RESTORE_PROCEDURE_INCOMPLETE: "RESTORE_PROCEDURE_INCOMPLETE",
  REVIEW_RECORD_NOT_FOUND: "REVIEW_RECORD_NOT_FOUND"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
