export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  DEVICE_NOT_OUTAGE: "DEVICE_NOT_OUTAGE",
  PAPERWORK_INCOMPLETE: "PAPERWORK_INCOMPLETE",
  OUTAGE_NOT_FOUND: "OUTAGE_NOT_FOUND",
  OUTAGE_WINDOW_INVALID: "OUTAGE_WINDOW_INVALID",
  OUTAGE_OVERLAP_DRAFT: "OUTAGE_OVERLAP_DRAFT",
  OUTAGE_BATCH_NOT_FOUND: "OUTAGE_BATCH_NOT_FOUND",
  OUTAGE_BATCH_NOT_RESUMABLE: "OUTAGE_BATCH_NOT_RESUMABLE",
  WRITE_FAILED: "WRITE_FAILED",
  CONFLICT_STATE: "CONFLICT_STATE"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
