"""业务异常码集中管理。service 与 controller 分别包装，禁止单点吞异常。"""

ERROR_CODES = {
    # 认证 / 鉴权
    "AUTH_REQUIRED": "AUTH_REQUIRED",
    "RBAC_DENIED": "RBAC_DENIED",
    # 通用
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "NOT_FOUND": "NOT_FOUND",
    "CONFLICT": "CONFLICT",
    "INTERNAL_ERROR": "INTERNAL_ERROR",
    # 停用时段
    "OUTAGE_WINDOW_NOT_FOUND": "OUTAGE_WINDOW_NOT_FOUND",
    "OUTAGE_WINDOW_INVALID_RANGE": "OUTAGE_WINDOW_INVALID_RANGE",
    "OUTAGE_ALREADY_CONFIRMED": "OUTAGE_ALREADY_CONFIRMED",
    "OUTAGE_DRAFT_VERSION_STALE": "OUTAGE_DRAFT_VERSION_STALE",
    "OUTAGE_RESUME_KEY_MISMATCH": "OUTAGE_RESUME_KEY_MISMATCH",
    "OUTAGE_WRITE_STAGE_UNKNOWN": "OUTAGE_WRITE_STAGE_UNKNOWN",
    # 容量 / 排期
    "BACKUP_CAPACITY_EXHAUSTED": "BACKUP_CAPACITY_EXHAUSTED",
    "ASSIGNMENT_NOT_FOUND": "ASSIGNMENT_NOT_FOUND",
    # 复役
    "DEVICE_NOT_OUT_OF_SERVICE": "DEVICE_NOT_OUT_OF_SERVICE",
    "RESTORE_PROCEDURE_INCOMPLETE": "RESTORE_PROCEDURE_INCOMPLETE",
    # 作废复核
    "REVIEW_RECORD_NOT_FOUND": "REVIEW_RECORD_NOT_FOUND",
}
