# 错误码集中定义。service 抛 ServiceException(code=...)，controller 再包一层，
# 不允许只在全局错误处理中间件里吞掉所有异常。
ERROR_CODES = {
    "AUTH_REQUIRED": "AUTH_REQUIRED",
    "RBAC_DENIED": "RBAC_DENIED",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "RATE_LIMITED": "RATE_LIMITED",
    "DEVICE_NOT_FOUND": "DEVICE_NOT_FOUND",
    "DEVICE_NOT_OUTAGE": "DEVICE_NOT_OUTAGE",
    "PAPERWORK_INCOMPLETE": "PAPERWORK_INCOMPLETE",
    "OUTAGE_NOT_FOUND": "OUTAGE_NOT_FOUND",
    "OUTAGE_WINDOW_INVALID": "OUTAGE_WINDOW_INVALID",
    "OUTAGE_OVERLAP_DRAFT": "OUTAGE_OVERLAP_DRAFT",
    "OUTAGE_BATCH_NOT_FOUND": "OUTAGE_BATCH_NOT_FOUND",
    "OUTAGE_BATCH_NOT_RESUMABLE": "OUTAGE_BATCH_NOT_RESUMABLE",
    "TASK_NOT_FOUND": "TASK_NOT_FOUND",
    "RESULT_NOT_FOUND": "RESULT_NOT_FOUND",
    "TICKET_NOT_FOUND": "TICKET_NOT_FOUND",
    "BUILDING_NOT_FOUND": "BUILDING_NOT_FOUND",
    "WRITE_FAILED": "WRITE_FAILED",
    "CONFLICT_STATE": "CONFLICT_STATE",
}
